name: Code Checking

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run Checks
        uses: ./.github/actions/checks

  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run Tests
        uses: ./.github/actions/tests
